### ISSUE TITLE
Text is improperly encoded in Sublime Console

### ISSUE THREAD

**Issue by hassankhan** [evgeny-golubev/SimplePHPUnit-for-Sublime-Text#1]
I'm not sure how this is happening, or if it is only on my machine, but my output looks like this:
![image](https://f.cloud.github.com/assets/1781985/976440/d98dd28a-068c-11e3-8e3d-6222a2761979.png)

**Comment by evgeny-golubev** [comment]
Thank you.

Fixed: https://github.com/m0nah/SimplePHPUnit-for-Sublime-Text/commit/fa675f542b8fae5cdb6b49d6c77f2e037a29f367.

**Comment by javorszky** [comment]
Hi there,

This might need reopening. I did a fresh install through sublime's package manager, and this is what I see: 
![screen shot 2014-04-01 at 14 59 50](https://cloud.githubusercontent.com/assets/1196299/2579814/f5c7a85a-b9a5-11e3-92d7-a8bbcbfb31a6.png)

Am I doing something wrong?
