### ISSUE TITLE
Error loading color scheme

### ISSUE THREAD

**Issue by marcioAlmada** [evgeny-golubev/SimplePHPUnit-for-Sublime-Text#2]
When executing `PHPUnit: Run` I get the following error message:

> Error loading colour scheme Packages/SimplePhpUnit/SimplePhpUnit.hidden-tmTheme: Unable to open Packages/SimplePhpUnit/SimplePhpUnit.hidden-tmTheme
- Test are run normally
- I can see PHPUnit correct output
- No colors in output

Problem occurs on linux/ubuntu 12.10 + Sublime Text 3

**Comment by marcioAlmada** [comment]
Still trying to figure out what's happening. Maybe color scheme contains errors?

**Comment by evgeny-golubev** [comment]
Fixed https://github.com/m0nah/SimplePHPUnit-for-Sublime-Text/commit/dd2e9d560ddec94cfced1ab5f658f382b2366ef7

**Comment by marcioAlmada** [comment]
Solved. Cheers!
